import PrimeryNavbar from '@/components/sidebar/PrimeryNavbar';
import './globals.css';

import { Raleway } from 'next/font/google';
import TopNavbar from '@/components/TopNavbar';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <>
        <body className={raleway.className}>
          <div>
            <PrimeryNavbar />
          </div>
          <div className="  main-content">
            <div className=" w-full h-full lg:ml-[265px] 2xl:ml-[200px]">
              <TopNavbar />
              {children}
            </div>
          </div>
        </body>
      </>
    </html>
  );
}
