import PrimeryNavbar from '@/components/sidebar/PrimeryNavbar';
import './globals.css';

import { Raleway } from 'next/font/google';
import TopNavbar from '@/components/TopNavbar';

const raleway = Raleway({ subsets: ['latin'] });

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <>
        <body className={raleway.className}>
          <main className=" flex w-full ">
            <div className=" basis-[45%] xl:basis-[35%] 2xl:basis-[30%] ">
              <PrimeryNavbar />
            </div>
            <div className="  w-full main-content">
              <div className=" w-full h-full ">
                <TopNavbar />
                {children}
              </div>
            </div>
          </main>
        </body>
      </>
    </html>
  );
}
